version: 2.1

jobs:
  arduino-ci-test:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: Install and test
          command: |
            bundle install
            bundle exec arduino_ci_remote.rb

workflows:
  arduino-ci-workflow:
    jobs:
      - arduino-ci-test
