name: Arduino CI

on: [push, pull_request]

jobs:
  runTest: 
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6
      - run: |
          bundle install
          bundle exec arduino_ci_remote.rb
